# Generated by Django 4.2 on 2023-05-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='no',
            field=models.CharField(max_length=13, null=True),
        ),
    ]
