# Generated by Django 4.2 on 2023-05-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_shipment_city_shipment_country_shipment_date1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='datetime',
        ),
        migrations.AddField(
            model_name='shipment',
            name='time1',
            field=models.TimeField(null=True),
        ),
    ]
