# Generated by Django 4.2 on 2023-05-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_shipment_datetime_shipment_time1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='country',
            new_name='city1',
        ),
        migrations.AddField(
            model_name='shipment',
            name='city2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='city7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='country1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='country2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date3',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date4',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date5',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date6',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='date7',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='msg7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time3',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time4',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time5',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time6',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='time7',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='firstname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='lastname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='no',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
