# Generated by Django 4.2 on 2023-05-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_city_shipment_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='time2',
            field=models.TimeField(null=True),
        ),
    ]
